trigger:
  branches:
    include:
    - main  # Set the branch name to trigger the pipeline

pr:
  branches:
    include:
    - '*'

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: Build Docker Image
    jobs:
    - job: BuildDockerImage
      displayName: Build and Push Docker Image
      steps:
      - script: |
          docker build -t $(ACR_NAME).azurecr.io/your-flask-app-image:$(Build.BuildId) .
          docker login -u $(ACR_USERNAME) -p $(ACR_PASSWORD) $(ACR_NAME).azurecr.io
          docker push $(ACR_NAME).azurecr.io/your-flask-app-image:$(Build.BuildId)

  - stage: Release
    displayName: Deploy to AKS
    dependsOn: Build
    jobs:
    - deployment: DeployToAKS
      displayName: Deploy to AKS
      environment: 'your-aks-environment' # Define the environment name for AKS
      strategy:
        runOnce:
          deploy:
            steps:
            - script: |
                # Add commands to deploy to AKS using kubectl or Helm
                # Example: kubectl apply -f kubernetes-manifests/app-deployment.yaml
